
CREATE TABLE REGISTRO (
    id_registro INTEGER NOT NULL,
    nombre_completo VARCHAR NOT NULL,
    ci INTEGER,
    fecha_nacimiento DATE,
    estado_civil VARCHAR,
    idioma_hablado VARCHAR,
    edad INTEGER,
    categoria_edad VARCHAR,
    genero VARCHAR,
    nro_carnet_discapacidad INTEGER,
    fechaExp_carnet_discapacidad DATE,
    fechaVen_carnet_discapacidad DATE,
    direccion_domicilio VARCHAR,
    otb_domicilio VARCHAR,
    distrito_domicilio VARCHAR,
    domicilio_verificado VARCHAR,
    lugar_origen VARCHAR,
    celular INTEGER,
    fallecido VARCHAR,
    tipo_discapacidad VARCHAR,
    grado_discapacidad VARCHAR,
    causa_discapacidad VARCHAR,
    beneficio_bono VARCHAR,
    independiente VARCHAR,
    familiar_acargo VARCHAR,
    afiliado_org VARCHAR,
    nombre_org VARCHAR,
    apoyo_tecnico VARCHAR,
    nombre_apoyo VARCHAR,
    tipo_medicamento VARCHAR,
    rehabilitacion VARCHAR,
    nombre_rehabilitacion VARCHAR,
    nombre_seguro_salud VARCHAR,
    intitucion_apoyo VARCHAR,
    grado_academico VARCHAR,
    nivel_academico VARCHAR,
    estudia VARCHAR,
    situacion_vivienda VARCHAR,
    generacion_ingresos VARCHAR,
    ocupacion VARCHAR,
    trabaja VARCHAR,
    insercion_laboral VARCHAR,
    fecha_registro DATE,
    motivo_consulta VARCHAR,
    situacion_actual VARCHAR,
    CONSTRAINT id_registro PRIMARY KEY (id_registro)
);

 \copy REGISTRO (id_registro, nombre_completo, ci, fecha_nacimiento, genero, direccion_domicilio, celular, tipo_discapacidad, grado_discapacidad, fecha_registro) FROM 'C:\Users\user\Desktop\Proyectos\DATOS_punata_limpio2.csv' WITH (FORMAT csv, HEADER true, DELIMITER ',');